name: catbox
description: View cats that are up for adoption.

dependencies:
  flutter:
    sdk: flutter

  firebase_core: 0.1.2
  firebase_auth: 0.5.3
  google_sign_in: 3.0.0
  cloud_firestore: 0.3.0
  font_awesome_flutter: 8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: 0.6.1

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: false

flutter:
  uses-material-design: true

  assets:
    - images/profile_header_background.png

  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
        - asset: fonts/Ubuntu-Bold.ttf
